### ISSUE TITLE
Feedback: Module imports

### ISSUE THREAD

**Issue by vmasrani** [UBC-MDS/ssg_pymeans#29]
Module imports not working - I couldn't get either the functions or the test to work. 
```python
>>> import ssg_pymeans
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/vmasrani/miniconda2/envs/swdev/lib/python2.7/site-packages/ssg_pymeans/__init__.py", line 1, in <module>
    from .ssg_pymeans import Pymeans, InvalidInput
  File "/Users/vmasrani/miniconda2/envs/swdev/lib/python2.7/site-packages/ssg_pymeans/ssg_pymeans.py", line 4, in <module>
    from ssg_pymeans.data import default_data
ImportError: No module named data
```

**Comment by guanchenz** [comment]
@vmasrani We have fixed this problem in milestone 3. It was caused by the csv data we used as a default dataset included in the package. This occurred only when doing fresh install so we did not catch this error during unit testing. We fixed it by using `pkg_resources` to properly add the csv data into the package.
